version: "3"

services:

  registry:
    image: registry:latest
    container_name: registry
    restart: always
    user: 1000
    ports:
      - 5000:5000
    volumes:
      - ~/data/registry:/var/lib/registry