version: "3"

services:

  mosquitto:
    image: localhost:5000/mosquitto:latest
    ports:
      - 1883:1883
      - 9001:9001

  node-red:
    image: localhost:5000/node-red:latest
    ports:
      - 1880:1880
    volumes:
      - /data/node-red:/data