version: "3"
services:
  node-red:
    build: ./node-red
    container_name: node-red
    restart: always
    ports:
      - 1880:1880
    volumes:
      - /data/node-red:/data

  mysql:
    build: ./mysql
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mysql:/var/lib/mysql