version: "3"

services:

  registry:
    build: ./registry
    container_name: registry
    restart: always
    ports:
      - 5000:5000
    volumes:
      - /data/registry/data:/var/lib/registry
      - /data/registry/config:/etc/docker/registry