version: "3"

services:

  # core services

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "1000:1000"
    ports:
      - 3306:3306
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    env_file:
      - ~/env/mariadb.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/mongodb:/data/db

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/influxdb:/var/lib/influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/mosquitto:/mosquitto/data

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    volumes:
      - ~/data/nginx/certs:/etc/ssl
    ports:
      - 80:80
      - 443:443

  # monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: "1000:1000"
    ports:
      - 3000:3000
    volumes:
      - ~/data/grafana:/var/lib/grafana

  # rv utilities

  nextcloud: # @todo use the fpm version so we can control the user permissions
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8000:80
    volumes:
      - ~/data/nextcloud:/var/www/html

  # rv automation

  node-red:
    image: nodered/node-red-docker
    container_name: node-red
    restart: always
    user: "1000:1000"
    ports:
      - 1880:1880
      - 10110:10110 # Pepwave MAX BR1 GPS Forwarding
    volumes:
      - ~/data/node-red:/data

  # build tools

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    user: "1000:1000"
    ports:
      - 8080:8080
    volumes:
      - ~/data/jenkins:/var/jenkins_home