version: "3"

services:

  # core services

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "1000:1000"
    ports:
      - 3306:3306
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    env_file:
      - ~/env/mariadb.env

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/mongodb:/data/db

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/influxdb:/var/lib/influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/mosquitto:/mosquitto/data

  # monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    user: "1000:1000"
    ports:
      - 3000:3000
    volumes:
      - ~/data/grafana:/var/lib/grafana

  # rv utilities

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    user: "1000:1000"
    ports:
      - 8080:80
    volumes:
      - ~/data/nextcloud:/var/www/html

  # rv automation

  node-red:
    image: nodered/node-red-docker
    container_name: node-red
    restart: always
    user: "1000:1000"
    ports:
      - 1880:1880
    volumes:
      - ~/data/node-red:/data