version: "3"

services:

  # databases

  mariadb:
    image: jsurf/rpi-mariadb
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes

  mongodb:
    image: localhost:5000/mongodb:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
      - 28017:28017
    volumes:
      - /data/mongodb/db:/data/db
  
  influxdb:
    image: hypriot/rpi-influxdb
    container_name: influxdb
    restart: always
    volumes:
      - /data/influxdb/data:/var/lib/influxdb
    ports:
      - 8086:8086

  # data processing

  mosquitto:
    build: ./mosquitto
    container_name: mosquitto
    restart: always
    ports:
      - 1883:1883
      - 9001:9001

  node-red:
    build: ./node-red
    container_name: node-red
    restart: always
    ports:
      - 1880:1880
    volumes:
      - /data/node-red:/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0