version: "3"

services:

  # core services

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "1000:1000"
    ports:
      - 3306:3306
    volumes:
      - ~/data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE: ~/secrets/mariadb-password

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/mongodb:/data/db

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/influxdb:/var/lib/influxdb

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: always
    user: "1000:1000"
    volumes:
      - ~/data/mosquitto:/mosquitto/data